<?php

/**
 * Implements hook_admin_paths().
 */
function admin_ux_panels_admin_paths() {
  $paths = array(
    'node/*/panel_content' => TRUE,
    'node/*/panel_layout' => TRUE,
  );
  return $paths;
}

/**
 * Implements hook_panels_new_pane_ater().
 *
 * Set the default style on newly created panes to "No markup at all".
 */
function admin_ux_panels_panels_new_pane_alter(&$pane) {
  $pane->style['style'] = 'naked';
}

/**
 * Implements hook_ctools_plugin_pre_alter().
 *
 * Remove some default ctools plugins not to confuse site builders.
 */
function admin_ux_panels_ctools_plugin_pre_alter(&$plugin, &$info) {
  switch ($plugin['plugin type']) {
    // Remove some default panels layouts.
    case 'styles':
      switch ($plugin['name']) {
        case 'rounded_corners':
        case 'block':
          $plugin = array();
          $info = array();
          break;
        case 'default':
          $plugin['title'] = t('With wrappers');
          break;
      }
      break;

    // Remove all default panels layouts.
    case 'layouts':
      switch ($plugin['module']) {
        case 'panels':
        //case 'zurb_foundation':
          $plugin = array();
          $info = array();
          break;
      }
      break;
  }
}

/**
 * Implementation of hook_ctools_content_subtype_alter()
 */
function admin_ux_panels_ctools_content_subtype_alter(&$subtype, &$plugin) {
  $category_label  = (is_string($subtype['category'])) ? $subtype['category'] : $subtype['category'][0];

  // Switch the labeling of "Miscellaneous" to "Blocks"
  if ($category_label == 'Miscellaneous') {
    $subtype['category'] = 'Blocks';
  }
}
